SELECT * FROM assignment.account;
desc assignment.account;

insert into account values(10,"ranjitha","rajajinagar",1000);
insert into account values(11,"ruchitha","hebbal",2000);
insert into account values(12,"neha","yelahanka",3000);
insert into account values(14,"pooja","jaynagar",4000);

ALTER TABLE assignment.account add phone_number BIGINT;

UPDATE ACCOUNT SET PHONE_NUMBER=8234567654 WHERE ACCOUNT_NUMBER=10;
UPDATE ACCOUNT SET PHONE_NUMBER=8234587656 WHERE ACCOUNT_NUMBER=11;
UPDATE ACCOUNT SET PHONE_NUMBER=7897654348 WHERE ACCOUNT_NUMBER=12;
UPDATE ACCOUNT SET PHONE_NUMBER=9686563079 WHERE ACCOUNT_NUMBER=13;
UPDATE ACCOUNT SET PHONE_NUMBER=7654322346 WHERE ACCOUNT_NUMBER=14;

SELECT * FROM ACCOUNT WHERE BRANCHNAME_ADDRESS IN("rajajinagar","hebbal");
SELECT * FROM ACCOUNT WHERE ACCOUNT_BALANCE BETWEEN 2000 AND 5000;

DELETE FROM ACCOUNT WHERE ACCOUNT_BALANCE=3000;

SELECT MIN(ACCOUNT_BALANCE)FROM ACCOUNT;
SELECT MAX(ACCOUNT_BALANCE)FROM ACCOUNT;
SELECT AVG(ACCOUNT_BALANCE)FROM ACCOUNT;
SELECT COUNT(ACCOUNT_BALANCE)FROM ACCOUNT;
truncate assignment.account;
DROP TABLE assignment.account;
DROP database assignment;











